# Generated by Django 3.2.12 on 2023-07-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20230707_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_start_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
