# Generated by Django 3.2.12 on 2023-07-09 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20230709_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winning_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
